### ISSUE TITLE
Cursor can not be moved upwards out of svelte editable component

### ISSUE THREAD

**Issue by zwz** [sibiraj-s/svelte-tiptap#18]
I tried the demo on https://sibiraj-s.github.io/svelte-tiptap/
1. locate the cursor on the first paragraph.
2. move the cursor downwards with arrow down key until the last paragraph (everything works well)
3. move the cursor upwards with arrow up key, you'll set it is stuck in the editable component.

If you try the the demo on [tiptap.dev ](https://tiptap.dev/guide/node-views/js#render-a-node-view-with-java-script), no such issue.

**Comment by sibiraj-s** [comment]
Thanks. Will check this. Sorry for the delay.

**Comment by aivo0** [comment]
I looked into this bug last year and as far as I could tell was that svelte-tiptap creates an extra wrapper div and there are known browser bugs and inconsistencies that apply then. I read about it on ProseMirror forum. You can compare https://sibiraj-s.github.io/svelte-tiptap/ on Chrome and Firefox and both act differently. On Firefox you cannot even get out of the editable Nodeview with both up and down arrows so the bug is even worse.  I even considered a work-around to listen to the keypresses and calculate the next cursor position but did not get to it. 
I think svelte-tiptap should remove the extra wrapper div.

**Comment by sibiraj-s** [comment]
Thanks @aivo0 . I did not notice your comment. Yes indeed that is the solution. Make sure to add `contenteditable=false` to the elements that are not intended to be edited.
